### ISSUE TITLE
Usability review

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#130]
Currently there is confusion about where functionalities should go in the editor, for everyone's reference here is what we are calling the different parts of the editor:

![image](https://user-images.githubusercontent.com/1327850/29377122-046db572-8278-11e7-9cd9-4731e6bcebfb.png)

**Comment by shorowit** [comment]
Some considerations:
- Where does the user create new objects (spaces, zones, windows, etc.)?
- What is the UI behavior for placing components (windows, doors, skylights, etc.)?
- Should e.g., window definitions and window instances be collapsed into just windows?  If so how would you add them and without having to enter a bunch of duplicate information for each window.
- Do we need a copy button (e.g., for space or window) that preserves properties (but not geometry)?
- Do we need a full screen library view once we get a lot of objects?

**Comment by macumber** [comment]
Here are my thoughts:

The model is divided into Geometry (anything under the stories element including spaces, shading, images, window instances, etc) and Resources (things that are shared across the entire model such as space_types, thermal_zones, window_definitions, etc).

- Navigator - this is used for moving around the Geometry hierarchy.  Story is always the first level object in the navigation tree.  You can select the type of geometry object space, shading, image) to show in the second level of the tree.  You can create geometry objects of the selected type, they will be children of the current story.  Components (windows and daylighting sensors) are placed using a specialized tool, they cannot be created without an x,y position in the drawing area.  Components (windows and daylighting controls) are not shown in the navigator tree, you can edit them in the library.  You can delete geometry objects from the tree.  I do not think resource objects (thermal_zone, building_unit, etc) should be shown in the tree.  If you select an object in the navigator tree and the the library is set up to view that type of object, then the selected object is scrolled to and selected in the library view.  If you select an object in the navigator tree, then that object is selected in the drawing area.

- Toolbar - This is where you select tools that modify geometry objects.  This is where I would put the option to render by thermal zone, space type, etc (current this is done by picking object type thermal zone in the navigator).  This is also where I would put the place component tool.  I would add an apply space property tool here, you can select which property to apply (space type, thermal zone, etc).  Then you can pick the exact thermal zone to apply, clicking on a space applies it.  This is similar to the place component tool.  I would suggest hiding undo/redo buttons once they are well tested.  I am not sure what the Fill tool is supposed to do.  

- Drawing Area - this shows the geometry related to the story currently selected in the navigator.  If you select an object in the drawing area and the navigator is displaying objects of that type, then that object is selected in the navigator tree.  If you select an object in the drawing area and the library is displaying that type of object, then the selected object is scrolled to and selected in the library view.

- Library - this is where you can edit detailed properties of anything in your model (geometry or resources), you can create and delete resources in this pane but you cannot create or delete geometry.  If you select an story in the library then the navigator moves to that story.  If you select a second level geometry object (space, shading, image) and that object is on the current story, then that object is selected in the navigator.  If you select an object in the library and that object is visible in the drawing area, then that object is selected in the drawing area.

- Menubar - this is for app level stuff like opening or saving a model, importing a library.  I am unclear if settings for the grid, etc should be on the menu bar or not, they seem ok there.

**Comment by asparke2** [comment]
I would change:
1. Move the grid spacing, story below, north axis to the Toolbar (they are related to drawing geometry)
2. Move the "Type" and "New" button to the left side of the top of the Library
3. Make the lines between the navigator, drawing area, and library movable so when we get more than a few objects you aren't stuck with really long scrolling in a tiny window.

**Comment by macumber** [comment]
Design in https://docs.google.com/document/d/1RPdgNoWUUs-DCzQSyClyNudzoE4bLxL_sFTDeL4CKNU/edit

**Comment by bgschiller** [comment]
I'm still making progress on this. Here are the latest set of assumptions I'm making based on the design document. Please correct me where I'm wrong, but I'm going to move forward with these assumptions otherwise.

"The eraser tool could also serve as a way to delete items" We can make this happen, but we currently keep the space around so you can add geometry: https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/59dd06a7d2d85c1c0e2c3af5/a92c5cb944bb5c63f6b342dbde105a9f/recording.webm

"This next mockup shows the Story panel expanded to show the add image button and also the properties for each story." Here's how it currently works (video): https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/59dd08cf7093b9f9cbb934cc/a565a1c43c0d895e8192d34b6cdf61d3/recording.webm
I feel like it is important to have the grid visible when adding images, for confirmation that it worked.

"We could have the image icon add a row with a selector" I don't understand why we want to show images directly in stories, rather than in the sub-story list (the way spaces are, and images currently). What would the options be if we had a select box as in the screenshot?

"If the user selects an image, only the move/size and erase tools are available" I did things a bit differently. I added a "Image" tool, which permits moving, resizing, and rotating images (but nothing else). Images can only be moved if the Image tool is selected. This seemed like it would solve some issues because spaces are right on top of images and it's not always clear which one is being clicked.

**Comment by shorowit** [comment]
A couple thoughts...

I agree that the space shouldn't be deleted when erasing the space's geometry. There's a separate mechanism for deleting the space, and frankly there's no harm to have a space around that doesn't have an associated geometry.

Regarding images, I continue to maintain that it would be a simpler UI to just allow a single image per story (on/off). If a user really needs multiple images per story, they can combine them outside the geometry editor. I also agree that as soon as the user selects an image, they should be presented with it on the grid for locating/sizing. It would also be nice if the image was centered in the viewable grid, rather than the top-left corner like it is now.

**Comment by shorowit** [comment]
With the new design implemented, I don't think this issue is relevant anymore.
