### ISSUE TITLE
Library Type isn't working

### ISSUE THREAD

**Issue by ljbrackney** [NatLabRockies/floorspace.js#151]
Changing Type in library pane isn't working.  e.g. Changing to Thermal Zone:

![thermalzone](https://user-images.githubusercontent.com/2230150/29496115-f3c117c6-8580-11e7-8a6e-94077402ac71.png)

The New button DOES add a thermal zone, but the library pane is not reflecting the new type setting or additional at all.

**Comment by ljbrackney** [comment]
This text is showing up in stdout:

js: TypeError: Cannot read property 'name' of undefined
js: Uncaught TypeError: Cannot read property 'name' of undefined

**Comment by macumber** [comment]
That output should be helpful, I have seen this too and it seems like something in the editor has crashed.  I wonder if there might be more information in the console errors.  To access those, you can set the following env variable before you launch the app:

    export QTWEBENGINE_REMOTE_DEBUGGING=3030

Then you can go to http://localhost:3030 in a chrome browser after you start the geometry editor page.

**Comment by macumber** [comment]
I'm considering setting this environment variable in the app for other users to help with debugging, let me know if you find it useful.  I think the one bummer is that you should open the connection in chrome before doing stuff that might crash the editor

**Comment by macumber** [comment]
@devKate we'll want to fix this, but hopefully we can get better output for you

**Comment by macumber** [comment]
Here's some output I got from this approach:

`embeddable_geometry_editor.html:120 init timetravel
embeddable_geometry_editor.html:123 saving state: Object
embeddable_geometry_editor.html:123 dispatching action: importLibrary
embeddable_geometry_editor.html:123 saving state: Object {triggeringAction: "importLibrary", state: Object}
embeddable_geometry_editor.html:123 dispatching action: geometry/createFaceFromPoints
embeddable_geometry_editor.html:123 dispatching action: models/updateSpaceWithData
embeddable_geometry_editor.html:123 saving state: Object {triggeringAction: "geometry/createFaceFromPoints", state: Object}
embeddable_geometry_editor.html:123 dispatching action: geometry/createFaceFromPoints
embeddable_geometry_editor.html:123 dispatching action: models/updateSpaceWithData
embeddable_geometry_editor.html:42 TypeError: Cannot read property 'name' of undefined(…)r @ embeddable_geometry_editor.html:42
embeddable_geometry_editor.html:123 saving state: Object {triggeringAction: "geometry/createFaceFromPoints", state: Object}
embeddable_geometry_editor.html:123 dispatching action: geometry/createFaceFromPoints
embeddable_geometry_editor.html:123 dispatching action: geometry/replaceFacePoints
embeddable_geometry_editor.html:123 dispatching action: models/updateSpaceWithData`

I'm hard to read line 42 of embeddable_geometry_editor.html because it is minified, maybe you know a trick @devKate ?

PS: I caused that error by drawing a second rectangle for space 1 that intersected with space 1, should have just made space 1 larger but it seemed to crash the app.

**Comment by macumber** [comment]
I can reproduce this on develop by drawing a rectangle in space 1, then drawing a second rectangle adjacent to it in space 1.  This needs to get fixed ASAP.

**Comment by bgschiller** [comment]
This is now working in develop
