### ISSUE TITLE
Import/Open/Save buttons disappear

### ISSUE THREAD

**Issue by shorowit** [NatLabRockies/floorspace.js#171]
Open the attached floorplan. The 3 buttons in the top-right disappear. 
[SFD_Multizone.json.txt](https://github.com/NREL/openstudio-geometry-editor/files/1246354/SFD_Multizone.json.txt)

It seems to work correctly for simpler floorplans.
[floorplan.json.txt](https://github.com/NREL/openstudio-geometry-editor/files/1246355/floorplan.json.txt)

cc @joseph-robertson

**Comment by shorowit** [comment]
This is probably related to https://github.com/NREL/openstudio-geometry-editor/issues/154?

**Comment by bgschiller** [comment]
@shorowit it's because we added a key: `showImportExport`. It appears in your simpler example but not your larger one.  Here's a version of the floorplan where I've added the key. https://trello-attachments.s3.amazonaws.com/58d428743111af1d0a20cf28/599de30931ca1b493f27a9ed/69b47b74b4e166ff3b6b412ebcfdbfa1/SFD_Multizone.json

I'll update the code to be backwards compatible.
