### ISSUE TITLE
Change project::config::units 

### ISSUE THREAD

**Issue by macumber** [NatLabRockies/floorspace.js#293]
enum should be 'ip' or 'si', default is 'ip', other default values in schema are evaluated in 'ip' units

**Comment by macumber** [comment]
If field has default and ip_units and si_units, assume default is in ip_units.  If app is in si units, convert defaults from ip_units to si_units

**Comment by shorowit** [comment]
To be clear, you can "assume default is in ip_units" because the schema specifies the default as ip in Project>properties>units>default.

I imagine that the only complication will be the case when the user opens the app and immediately changes from ft to m, as there can be existing objects (e.g., stories) already defined whose properties would need to be updated.

Also note that beyond the ft<->m conversion, there is a lux<->fc conversion for illuminance.

**Comment by shorowit** [comment]
The change was made. We have a separate ticket for allowing the user to change the units on the fly -- https://github.com/NREL/floorspace.js/issues/169.

**Comment by jgunstone** [comment]
how does one change the project units by default to SI ?

**Comment by macumber** [comment]
@jgunstone are you 1) embedding FloorspaceJS in your own application, 2) using it in the OpenStudio Application, or 3) using it online at https://openstudiocoalition.org/floorspace.js/

**Comment by jgunstone** [comment]
hi - thanks for the quick response - 
currently just using it online https://openstudiocoalition.org/floorspace.js/
but also interested in embedding FloorspaceJS in my own application...
