### ISSUE TITLE
Broken Geometry Bug

### ISSUE THREAD

**Issue by fsudaman** [NatLabRockies/floorspace.js#302]
It appears that making any geometry change and merging will result in the object state being corrupted. This issue can be reproduced by the following steps (OSM file attached) 
[FloorSpace Broken Geometry Bug - Reproduction.zip](https://github.com/NREL/floorspace.js/files/1746522/FloorSpace.Broken.Geometry.Bug.-.Reproduction.zip)

- Overwriting geometry with new spaces
- Erasing part of an existing space
- Creating a new space, without overwriting any previous areas

All three, once merged, resulted in the bugs such as below appearing (checked by creating a few new floors and trying to draw new spaces)

- Trying to draw new surfaces on fresh floors produces very strange results. When using the rectangle tool, each click creates a line, rather than a rectangular space, the space cannot be ‘finalised’, and when these lines form closed areas, they are filled in with colour (See screenshot, attached).
- Attempting to modify existing surfaces results in the unexpected distortions seen previously, however it now seems to affect every surface.
- Creating new floors doesn’t seem to work as intended (Eg If creating 2+ new floors, the new floors can’t be individually selected. Instead all floors are selected together, and they each create a new space for the first floor in the selection, see screenshot2, attached)
- The above behaviour seems to be replicated when creating any new list items (Spaces, zones, windows, constructions, etc)
- The display seems to not respond properly when viewing a new floor. The floor below is simply the last floor viewed, regardless of its position, and you can’t draw yourself away from the centre of the drawing.

![floorspace broken geometry bug screenshot](https://user-images.githubusercontent.com/9958226/36518678-922a0ffc-17db-11e8-8b0c-4a18d0a5cbab.png)

![floorspace broken geometry bug screenshot2](https://user-images.githubusercontent.com/9958226/36518692-a10ebec8-17db-11e8-9909-a606a2628b18.png)

**Comment by macumber** [comment]
Moved to https://github.com/NREL/OpenStudio/issues/3008

**Comment by macumber** [comment]
@fsudaman thank you for the very detailed report.  Please note, that issues related to the FloorspaceJS widget embedded inside the OpenStudio Application (including translation to OSM and merging with OSM) should be reported in the OpenStudio repository.  This repository is for issues with the JavaScript FloorspaceJS widget only

**Comment by rwadhwa910** [comment]
@macumber is there a solution for this I see it was opened in 2018.

**Comment by macumber** [comment]
I'm not sure which bug you are referring to @rwadhwa910?  It looks like a issue with file change counters might have been fixed recently with:

https://github.com/NREL/floorspace.js/pull/379

That change is not yet incorporated with the OpenStudio Application, I may see if it is something we can include in our next release:

https://github.com/openstudiocoalition/OpenStudioApplication/issues/327

This bug was moved to OpenStudio and is still open: https://github.com/NREL/OpenStudio/issues/3008

Right now it is not tagged for the next release.  If you are seeing specific issues with the import/merge of Floorspace JSON files in the OpenStudio Application please add them to the bug in the OpenStudio Application repo.
